
polar_terms = ['2019', '2020', 'abc', 'abortion', 'access', 'accused', 'adam',
       'added', 'administration', 'admitted', 'adviser', 'advocates',
       'afternoon', 'agency', 'aid', 'alexandria', 'allegations',
       'alleged', 'allegedly', 'allies', 'amendment', 'america', 'amy',
       'andrew', 'biden', 'biggest', 'bit', 'block', 'bloomberg', 'bush',
       'campaigns', 'care', 'center', 'central', 'chair', 'chairman',
       'change', 'china', 'chinese', 'chuck', 'claimed', 'claims', 'cnn',
       'companies', 'conditions', 'congress', 'congressional',
       'conservative', 'conspiracy', 'continued', 'controversial',
       'corporate', 'courts', 'cycle', 'data', 'days', 'dca', 'defense',
       'democrat', 'democrats', 'described', 'disease', 'domestic',
       'donald', 'effort', 'efforts', 'emails', 'experts', 'facts',
       'failed', 'familiar', 'fbi', 'fellow', 'finance', 'financial',
       'foundation', 'fox', 'giuliani', 'gop', 'group', 'groups',
       'growing', 'guns', 'hall', 'healthcare', 'helped', 'hunter',
       'idea', 'illegal', 'immigrant', 'immigrants', 'impeach',
       'important', 'increasingly', 'industry', 'influence', 'inspector',
       'interference', 'internal', 'investigations', 'investigators',
       'ivt', 'james', 'joe', 'kamala', 'key', 'known', 'largely',
       'later', 'lawmakers', 'lawsuit', 'left', 'liberal', 'likely',
       'little', 'long', 'longtime', 'major', 'mayor', 'media',
       'medianame', 'monday', 'money', 'months', 'mr', 'msnbc', 'nancy',
       'nominee', 'ocasiocortez', 'official', 'officials', 'page', 'past',
       'pelosi', 'personal', 'policy', 'politics', 'potentially',
       'powerful', 'pressure', 'pretty', 'prior', 'probe', 'project',
       'prominent', 'public', 'questions', 'radical', 'reality',
       'reelection', 'regarding', 'related', 'reported', 'representative',
       'republican', 'republicans', 'responded', 'revealed', 'rhetoric',
       'rights', 'rightwing', 'role', 'rudy', 'said', 'saying', 'says',
       'scandal', 'schiff', 'senator', 'sign', 'socialist', 'speaker',
       'spent', 'spokesperson', 'stated', 'stories', 'strategy', 'summer',
       'sunday', 'taken', 'terrorist', 'theory', 'think', 'town',
       'transcript', 'trumps', 'tweet', 'tweeted', 'unprecedented',
       'vermont', 'vice', 'video', 'want', 'watch', 'ways', 'wednesday',
       'weeks', 'white', 'widely', 'year']